spring:
  application:
    name: java_backend

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.dxgzfugilsceplbhvkhl
    password: REMOVED

  jpa:
    hibernate:
      ddl-auto: create

    # show-sql: true

    properties:
      hibernate:
        format_sql: true

mqtt:
  url: "tcp://localhost:1883"
  username: "user1"
  password: "akshay"
  default:
    client:
      id: "spring"

calendar:
  google:
    application-name: ESP Assistant Calendar Tool
    credentials-file: classpath:credentials.json
    calendar-id: akwork6124@gmail.com
    timezone: Asia/Kolkata

notion:
  api:
    token: ${NOTION_TOKEN}
    version: "2022-06-28"
    page-id: 3db54d38bea18014b882e5de2298bbd5

logging:
  level:
    org:
      hibernate: 
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
